server:
  port: 8090    #default port where the service will be started

eureka:
  registerwithEureka: true
  fetchregistry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://172.23.239.170:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: muzix-rest-mongoDB   #current service name to be used by the eureka server

  cloud:
    config:
      uri: http://172.23.239.164:8088

  data:
    mongodb:
      host: 172.23.239.150
      database: admin